services:
  task_manager:
    image: task_manager
    container_name: task_manager_container
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
        - "6379:6379"
    restart: unless-stopped

